language: python

python:
  - "3.5"

branches:
  only:
    - master
    - develop

cache:
  pip: true
  directories:
    - $HOME/nltk_data

before_install:
  - pip install --no-clean git+https://github.com/Rostlab/nalaf.git@develop
  - printf 'nalaf commit: ' && cd /tmp/pip-*-build && git rev-parse HEAD  # **nalaf**: log the exact commit for debugging purposes --  # if needed, we could grep out the exact build folder as in: grep -o "/[^ ]*/pip-.*-build"
  - python -m nalaf.download_corpora
  - pip install codecov pytest-cov
  - cd $TRAVIS_BUILD_DIR

install:
  - printf 'relna commit: ' && git rev-parse HEAD  # **relna**: log the exact commit for debugging purposes
  - pip install .
  - python -m relna.download_corpora

script:
  - time py.test -s -v --cov=./

after_success:
  - codecov
